### ISSUE TITLE
登录邮箱检验失败

### ISSUE THREAD

**Issue by MuXiaoYun** [thuhole/thuhole-go-backend#103]
![图片](https://user-images.githubusercontent.com/108248439/221098885-dd634b80-2ba7-43f0-8133-868b76652486.png)

**Comment by zekkizoe** [comment]
一样

**Comment by MuXiaoYun** [comment]
> 

旧树洞关停了，移步新T树洞，我close issue了

**Comment by zekkizoe** [comment]
新树洞链接在哪找



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月30日(周二) 晚上6:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [treehollow/treehollow-backend] 登录邮箱检验失败 (Issue #103)




   
旧树洞关停了，移步新T树洞，我close issue了
