### ISSUE TITLE
希望能取消邮箱验证，这里提供一种匿名的验证方式

### ISSUE THREAD

**Issue by mcfx0** [thuhole/thuhole-go-backend#13]
自建 NS 服务器，用户连接清华网络（或 vpn）后，通过校内 dns（我最开始想到的是 101.6.6.6，但是此 dns 在其他一些学校也可用，后经人提醒可以使用 166.111.8.28）解析某个指定域名，收到这一请求即验证成功（或者也可以将 token 放在解析结果中）。

这个验证方法可以保证网站管理员和用户都是匿名的。

**Comment by thuhole** [comment]
最简单的就是，只允许T大IP访问。但是，现在疫情期间，连接VPN会很不方便。

**Comment by mcfx0** [comment]
> 最简单的就是，只允许T大IP访问。但是，现在疫情期间，连接VPN会很不方便。

所以才想到了这种扭曲的验证方式。
