### ISSUE TITLE
后端校验 TOKEN

### ISSUE THREAD

**Issue by Rapiz1** [thuhole/thuhole-go-backend#14]
目前非注册用户在 localStorage 里随便加一条 TOKEN 就可以浏览树洞。不知道是不是有意为之。
![image](https://user-images.githubusercontent.com/20105061/85220772-f6083280-b3e0-11ea-8a94-f2658c3fbb87.png)

**Comment by thuhole** [comment]
feature

**Comment by panda2134** [comment]
#29 修了之后这个最好也修一下
