### ISSUE TITLE
希望树洞提供富文本支持

### ISSUE THREAD

**Issue by Gravifer** [thuhole/thuhole-go-backend#15]
目前的官方置顶是一份裸markdown,如果能够渲染是不是更棒?
加入latex支持也许会增添更多乐趣(

**Comment by thuhole** [comment]
PR is very welcome!

**Comment by panda2134** [comment]
讨论：是否应该只允许洞主写markdown? 因为回复的渲染位置和过于复杂的markdown有点不搭、、、

**Comment by panda2134** [comment]
我正在弄markdown支持
（这个issue是不是应该提到前端的repo

**Comment by Gravifer** [comment]
（提的时候还没发现前端放在哪个repo

**Comment by Yixuan-Wang** [comment]
Markdown block 的样式（尤其是标题）似乎会使得界面变得有些混乱，分散注意力……个人理解，一条树洞与一条帖子的定位是不同的，更像是一句话，而不是一篇文章（当然这是见仁见智的问题了）。如果只解析 inline 语法的话，也会有轻微的干扰，比如搜索关键词默认会将关键词加粗，这会和 markdown 的样式冲突，同时有些颜文字，比如 (\*｀▽´\*)，显示也会不正常（这就需要权衡了，要看是使用颜文字的需求大，还是 markdown 的需求大）。
![Snipaste_2020-06-22_09-54-34](https://user-images.githubusercontent.com/21151119/85241451-6741f700-b46e-11ea-99ff-08f989208a4a.png)
![Snipaste_2020-06-22_09-55-59](https://user-images.githubusercontent.com/21151119/85241653-21d1f980-b46f-11ea-867a-65609ad60d01.png)

**Comment by panda2134** [comment]
主要是在处理markdown的同时也要考虑原来的洞主渲染、pid渲染等规则

**Comment by panda2134** [comment]
我那个pr改了下 现在洞主渲染应该是正常了

**Comment by panda2134** [comment]
supported，可以close了

https://github.com/thuhole/webhole/pull/3
