### ISSUE TITLE
树洞回复时出现错乱

### ISSUE THREAD

**Issue by VicaYang** [thuhole/thuhole-go-backend#17]
问题#1350下 #6552 #6553应该是两个人发的，但都认证为[Isabella]

**Comment by thuhole** [comment]
有可能是goroutine并发访问MySQL的问题。

**Comment by thuhole** [comment]
#4645又出现了
看起来需要一个Comment Lock

**Comment by VicaYang** [comment]
支持，不过这个问题影响不是特别大，估计配合着#20一并修了就好。

**Comment by thuhole** [comment]
好像修复了
