### ISSUE TITLE
收验证码邮件延迟较长

### ISSUE THREAD

**Issue by thuhole** [thuhole/thuhole-go-backend#2]

**Comment by rcy17** [comment]
猜想可能和邮件推送服务有关？看了下代码用的mailgun的服务，我没接触过，此前我自己开发的网站后端用的阿里云的免费邮箱推送，当时测试了下多数邮箱能秒到（不能秒到的我们测出了微软邮箱），包括清华的邮箱，并且不会到垃圾箱。或许可以考虑换个服务试试？

**Comment by thuhole** [comment]
@rcy17 感谢您的建议！抱歉我前两天没看到这条消息，我最近试试看。
