### ISSUE TITLE
树洞移动客户端

### ISSUE THREAD

**Issue by UNIDY2002** [thuhole/thuhole-go-backend#23]
受PKU Helper启发，我从半年前开始开发一款类似的APP，这是[仓库链接](https://github.com/UNIDY2002/THUInfo)，现已做出Android版本，并计划在暑假将其迁移至React Native。（但由于一直没有返校，也一直没有推广的机会。）
现在看到我们也有自己的树洞了，我打算借此机会将两者融合一下（类似PKU Helper），不知是否妥当？
（当然，如果是这样，我可以考虑加快我这里开发与迁移的进度。）

**Comment by thuhole** [comment]
可以！欢迎！如果需要可以放友情链接。

**Comment by UNIDY2002** [comment]
谢谢！
