### ISSUE TITLE
【Feature request】链接预览

### ISSUE THREAD

**Issue by Gravifer** [thuhole/thuhole-go-backend#26]
可以利用 [https://linkpreview.net/](LinkPreview.net) 的 API 实现洞文中链接的预览。
目前虽然洞文总量大，附加链接的洞文比例不高，免费版的 60请求/小时应该已能满足需求。

**Comment by thuhole** [comment]
idea不错，但linkpreview.net我觉得不可，因为我觉得还是应该尽量减少第三方服务的使用。

**Comment by thuhole** [comment]
感觉界面不好设计，先不加这功能了
