### ISSUE TITLE
Markdown文档

### ISSUE THREAD

**Issue by thuhole** [thuhole/thuhole-go-backend#27]
帮助新手学会Markdown基本用法

**Comment by Gravifer** [comment]
可以先在置顶给个 link 到 [https://www.runoob.com/markdown/md-tutorial.html](Runoob)
有不少特性不同，不过学会基本语法应该足够

**Comment by thuhole** [comment]
> 可以先在置顶给个 link 到 [https://www.runoob.com/markdown/md-tutorial.html](Runoob)
> 有不少特性不同，不过学会基本语法应该足够

感觉这个link有些啰嗦，我觉得可以找个更精简的教程。毕竟，最主要的功能其实就是加粗之类的，TeX只是用来玩的。

**Comment by thuhole** [comment]
replaced by https://github.com/thuhole/webhole/issues/6
