### ISSUE TITLE
关于信息泄露的问题

### ISSUE THREAD

**Issue by zhou-zl18** [thuhole/thuhole-go-backend#29]
https://thuhole.com/services/thuhole/api.php?action=getone&pid=1
通过这个url无需登录即可查看树洞信息，可能被校外人士利用。
本人不太懂网站搭建，偶然发现，不知能否解决？

**Comment by thuhole** [comment]
暂不修复

**Comment by yzs981130** [comment]
更新一下已经修了？

**Comment by thuhole** [comment]
@yzs981130 修了。
