### ISSUE TITLE
进入树洞app便黑屏

### ISSUE THREAD

**Issue by YupuLu** [thuhole/thuhole-go-backend#30]
可以见到一瞬间树洞，然后就变成如图所示的黑屏情况。
![Screen Shot 2020-06-23 at 9 07 16 AM](https://user-images.githubusercontent.com/45250804/85349511-3aa2e380-b531-11ea-92f9-f39faa480e1e.png)

**Comment by thuhole** [comment]
看起来是由于Markdown渲染空树洞的时候会崩溃

**Comment by thuhole** [comment]
疑似修复，请@panda2134 看一下PR里和这个fix里有没有什么bug

**Comment by panda2134** [comment]
好，我来看

**Comment by YupuLu** [comment]
似乎已经修复，谢谢！
