### ISSUE TITLE
一个 typo

### ISSUE THREAD

**Issue by Alan-Liang** [thuhole/thuhole-go-backend#42]
<https://github.com/thuhole/thuhole-go-backend/blob/87fb4e8eb5c48463f08f5791fb6633f82709bbed/pkg/route/routeApiPOST.go#L273>

应该是「关注失败」而非「举报失败」

**Comment by thuhole** [comment]
https://github.com/thuhole/thuhole-go-backend/commit/bd92911dcb21fba34a08e1db6b1c00dbcb3daa70 fixed
非常感谢！
