### ISSUE TITLE
搜索关键词"tag"无法搜到任何内容

### ISSUE THREAD

**Issue by thuhole** [thuhole/thuhole-go-backend#43]
![image](https://user-images.githubusercontent.com/66957922/85947850-bbbe0880-b97f-11ea-960f-d44600ddd16f.png)

**Comment by thuhole** [comment]
疑似
```
FULLTEXT INDEX (text) WITH PARSER ngram
```
和
```
match(text) against(? IN BOOLEAN MODE)
```
里的MySQL自己的问题？

**Comment by thuhole** [comment]
```
select * from posts where match(text) against ('+tag' in boolean mode);
Empty set (0.00 sec)
```

**Comment by yzs981130** [comment]
feature的label笑死我了

**Comment by thuhole** [comment]
> feature的label笑死我了

这个bug我至今迷惑，不知道你有没有什么想法？
后端是MySQL 8.0，ngram token size是2。P大树洞的搜索应该也是MySQL的Boolean mode搞的，能观察到一些类似的特性，但估计是MySQL 5.x。

**Comment by yzs981130** [comment]
> > feature的label笑死我了
> 
> 这个bug我至今迷惑，不知道你有没有什么想法？
> 后端是MySQL 8.0，ngram token size是2。P大树洞的搜索应该也是MySQL的Boolean mode搞的，能观察到一些类似的特性，但估计是MySQL 5.x。

`tag`是MySQL的boolean下面的关键字吗？我研究研究

**Comment by thuhole** [comment]
以解决。以root运行以下命令：
```sql
CREATE TABLE empty_stopwords(value VARCHAR(30)) ENGINE=INNODB;
set global innodb_ft_server_stopword_table = 'dbname/empty_stopwords';
OPTIMIZE TABLE posts;
```

**Comment by thuhole** [comment]
在mysql配置文件中，也需要设置
```
innodb_ft_server_stopword_table=dbname/empty_stopwords
```
才可以在mysql重启后确保bug不会重新出现。
