### ISSUE TITLE
[bug] doPost函数检查type可能导致非预期结果

### ISSUE THREAD

**Issue by yzs981130** [thuhole/thuhole-go-backend#45]
`type`来源于用户post，可能不正确

**Comment by thuhole** [comment]
我现在对type判断是，如果是image则是image，否则是text。
可能更好的方法是要对post data中的data进行图片格式检验，顺便做个鉴黄之类的。

**Comment by yzs981130** [comment]
![image](https://user-images.githubusercontent.com/15307797/86373008-7ec28080-bcb5-11ea-92d9-a4e6e5e04a12.png)
乌乌能给我先解了吗

**Comment by yzs981130** [comment]
> 我现在对type判断是，如果是image则是image，否则是text。
> 可能更好的方法是要对post data中的data进行图片格式检验，顺便做个鉴黄之类的。

12651也麻烦删一下
