### ISSUE TITLE
[Feature Request] "允许的邮箱后缀"作为可配置项?

### ISSUE THREAD

**Issue by leoleoasd** [thuhole/thuhole-go-backend#50]
如题, 既然是AGPL协议开源, 那么理论上是欢迎外校搭建/外校开发者做出贡献的. 但是现有的代码中, 可选的邮箱后缀是hard coded的, 不方便外校开发者贡献/调试/搭建. 是否考虑将允许的邮箱后缀作为可配置项?

如果接受的话, 我可以写个pr.

**Comment by thuhole** [comment]
感谢您的建议！
把邮箱后缀判定变为regex放到配置文件里确实是个好主意。

为了方便外校同学部署，也许还需要做更多优化，比如加些注释、精简一下config.json（把非必填的项单拎出来）之类。此Issue可以成为#20 的一部分了。

**Comment by thuhole** [comment]
fixed in `next` branch
