### ISSUE TITLE
为提升图片访问速度，考虑使用GitHub+jsdelivr作为图床

### ISSUE THREAD

**Issue by thuhole** [thuhole/thuhole-go-backend#51]

**Comment by yzs981130** [comment]
感觉教育网内这个不如cloudflare，外面可能jsdelivr快一点

**Comment by thuhole** [comment]
确实，但是现在是假期，没办法

**Comment by yzs981130** [comment]
- 腾讯云有6个月的cdn+cos新人券，挺快的，六个月以后要pay
- 七牛有免费的http的
- 以前又拍好像也有免费的最近不知道了
- 国外的就sm.ms也挺快，用也方便

或者如果存的问题很好解决的话，找找便宜cdn也不错，但是速度就不知道了

**Comment by thuhole** [comment]
> * 腾讯云有6个月的cdn+cos新人券，挺快的，六个月以后要pay
> * 七牛有免费的http的
> * 以前又拍好像也有免费的最近不知道了
> * 国外的就sm.ms也挺快，用也方便
> 
> 或者如果存的问题很好解决的话，找找便宜cdn也不错，但是速度就不知道了

现在用着的是Azure CDN的试用hhhbabaoguio'gui

**Comment by thuhole** [comment]
主要是每个月流量太大了，图片300G以上的流量，付费CDN基本都可以刷掉了

**Comment by thuhole** [comment]
用GitHub当图床很有可能被GitHub当成abuse删号了，所以保险起见这个方案还是放弃吧。

**Comment by yzs981130** [comment]
草300G可以，以后会放放那种统计数据吗，感觉也挺有意思；
图片感觉以后可以整压缩和lazy load之类的；
我昨天试了一哈rclone挂google drive，然后前端跑cloudflare workers走cloudflare，感觉可以作为存储上的0成本解决方案；网络的话cf教育网内100M随便跑还是很舒服

**Comment by yzs981130** [comment]
而且300G好像cf不要钱的

**Comment by thuhole** [comment]
> 而且300G好像cf不要钱的

对，cf基本上是唯一解决方案了。

**Comment by thuhole** [comment]
> 草300G可以，以后会放放那种统计数据吗，感觉也挺有意思；
> 图片感觉以后可以整压缩和lazy load之类的；
> 我昨天试了一哈rclone挂google drive，然后前端跑cloudflare workers走cloudflare，感觉可以作为存储上的0成本解决方案；网络的话cf教育网内100M随便跑还是很舒服

现在的话大概一天UV 2k人左右，PV 13k次，估计大约是P洞的1/3。
存储上，感觉持续运行一年也超不过几十G，应该不是问题。顺便，cloudflare workers不是要钱的吗？

**Comment by yzs981130** [comment]
> > 草300G可以，以后会放放那种统计数据吗，感觉也挺有意思；
> > 图片感觉以后可以整压缩和lazy load之类的；
> > 我昨天试了一哈rclone挂google drive，然后前端跑cloudflare workers走cloudflare，感觉可以作为存储上的0成本解决方案；网络的话cf教育网内100M随便跑还是很舒服
> 
> 现在的话大概一天UV 2k人左右，PV 13k次，估计大约是P洞的1/3。
> 存储上，感觉持续运行一年也超不过几十G，应该不是问题。顺便，cloudflare workers不是要钱的吗？

基础版8要钱，有request数限制，一天10w，不够了多开号就行了
免费版worker没有KV storage，当serverless用就行了，我们这种有server有数据库的也用不到他的KV，感觉是真滴好用
感觉cf挺好的，还能防CC，不然只要是自己pay的服务被打了就滴血
sm.ms康康？只用过免费的，速度够，可能没那么方便，没用过sdk

**Comment by thuhole** [comment]
> > > 草300G可以，以后会放放那种统计数据吗，感觉也挺有意思；
> > > 图片感觉以后可以整压缩和lazy load之类的；
> > > 我昨天试了一哈rclone挂google drive，然后前端跑cloudflare workers走cloudflare，感觉可以作为存储上的0成本解决方案；网络的话cf教育网内100M随便跑还是很舒服
> > 
> > 
> > 现在的话大概一天UV 2k人左右，PV 13k次，估计大约是P洞的1/3。
> > 存储上，感觉持续运行一年也超不过几十G，应该不是问题。顺便，cloudflare workers不是要钱的吗？
> 
> 基础版8要钱，有request数限制，一天10w，不够了多开号就行了
> 免费版worker没有KV storage，当serverless用就行了，我们这种有server有数据库的也用不到他的KV，感觉是真滴好用
> 感觉cf挺好的，还能防CC，不然只要是自己pay的服务被打了就滴血
> sm.ms康康？只用过免费的，速度够，可能没那么方便，没用过sdk

感谢!
cloudflare确实太好用了。。不过一天10w的次数也容易被DoS之类。
防CC的话只要服务带这个功能其实就行，thuhole.com整套CDN都防CC。
sm.me我记得i.loli.net还是解析到cloudflare上的，很无语。

**Comment by yzs981130** [comment]
方便回一个或者邮件回一下目前图床的流量和UV PV以及成本？有做cdn的联系我可以帮忙问问价~
