### ISSUE TITLE
https://thuhole.com/##82197  网页版点开大图会404

### ISSUE THREAD

**Issue by yzs981130** [thuhole/thuhole-go-backend#62]
没仔细看。。
https://img2.thuhole.com/7g/7gxeu23dvzbye23yxflzg4mvcbf5u2qk.jpeg 这个正常
href到 https://thimg.yecdn.com/7g/7gxeu23dvzbye23yxflzg4mvcbf5u2qk.jpeg 这个404

**Comment by thuhole** [comment]
哈哈哈，我们现在有鉴黄系统

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by yzs981130** [comment]
666666
