### ISSUE TITLE
config.json由json格式改为hjson或yaml等human friendly格式

### ISSUE THREAD

**Issue by thuhole** [thuhole/thuhole-go-backend#65]

**Comment by yzs981130** [comment]
yaml用这个 https://github.com/go-yaml/yaml

**Comment by thuhole** [comment]
嗯嗯感谢！我们用的https://github.com/spf13/viper 应该自带yaml支持

**Comment by thuhole** [comment]
https://github.com/thuhole/thuhole-go-backend/commit/dc7e91e8d3f1a272e8ecffc78df715ee32f16ea4 fixed
