### ISSUE TITLE
配置文档sha256sum算法问题-From PKUHollow

### ISSUE THREAD

**Issue by pkuhollow** [thuhole/thuhole-go-backend#78]
经过验证，示例配置文件中的
```
echo 'xxx' | sha256sum
```
生成hash和go生成的hash值不一样,导致校验失败

使用[emn178.github.io](https://emn178.github.io/online-tools/sha256.html)生成的sha256sum和go生成的一致

**Comment by thuhole** [comment]
感谢提醒！

**Comment by thuhole** [comment]
fixed https://github.com/thuhole/thuhole-go-backend/commit/a2d12eb1d3e1a3ba50981c9e5ba05795a2989cf8

**Comment by Alan-Liang** [comment]
FYI，正确的方式应该是 `echo -n 'xxx' | sha256sum`，那个 `-n` 表示不在最后按照 UNIX 习惯加一个换行。

**Comment by thuhole** [comment]
> FYI，正确的方式应该是 `echo -n 'xxx' | sha256sum`，那个 `-n` 表示不在最后按照 UNIX 习惯加一个换行。

你说得很有道理
