### ISSUE TITLE
期待能允许官方校友邮箱用户参与注册树洞

### ISSUE THREAD

**Issue by FrancoisHohenzollern** [thuhole/thuhole-go-backend#9]
毕业生毕业后一段时间（最多半年？）后就无法再通过 @mails.tsinghua.edu.cn 邮箱收件，但毕业时也会收到一个学校统一授予的官方校友邮箱 @tsinghua.org.cn 。考虑到 @tsinghua.org.cn 同样具有甄别校友身份的官方属性，可否允许持有 @tsinghua.org.cn 的用户参与注册树洞？

**Comment by Yixuan-Wang** [comment]
P大树洞是不允许校友访问的……

**Comment by FrancoisHohenzollern** [comment]
> P大树洞是不允许校友访问的……

emmm 虽然但是  比如6字班马上毕业了，不就变成校友了。。。如果他们可以继续访问，为什么比如5字班已经毕业的就不可以呢T-T

**Comment by Yixuan-Wang** [comment]
P大树洞所有的毕业生都会失去访问权限，因为走的是官方IAAA认证，而且每三个月必须重新认证一次，毕业以后认证就无法通过了，自然就失去访问权限了……（我也不是很了解，应该是这样吧）

**Comment by FrancoisHohenzollern** [comment]
啊这样  那就太难了

**Comment by FrancoisHohenzollern** [comment]
> P大树洞所有的毕业生都会失去访问权限，因为走的是官方IAAA认证，而且每三个月必须重新认证一次，毕业以后认证就无法通过了，自然就失去访问权限了……（我也不是很了解，应该是这样吧）

啊这样 那就太难了

**Comment by thuhole** [comment]
能理解您对母校的留恋，但我们目前觉得这个最好还是一个仅在校生的社区。等树洞成熟后，我们考虑给校友开放读取权限，但可能不会开放发帖权限。

**Comment by FrancoisHohenzollern** [comment]
> 能理解您对母校的留恋，但我们目前觉得这个最好还是一个仅在校生的社区。等树洞成熟后，我们考虑给校友开放读取权限，但可能不会开放发帖权限。

哈哈哈谢谢！辛苦开发啦~（虽然我是一个在校菜狗，但是留恋母校是真的hhh
